apiVersion: v1
kind: Pod
apiVersion: v1
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: redis
    ports:
      - containerPort: 80
    volumeMounts:
    - name: test
      mountPath: '/data/redis'
  volumes:
    - name: test
      emptyDir: {}